require 'rubygems'
require 'bundler'
Bundler.require
require 'rake/testtask'

task :default => :test

file "lib/grammar.kpeg.rb" => ["lib/grammar.kpeg"] do
  Dir.chdir "lib" do
    system "rm grammar.kpeg.rb"
    system "kpeg grammar.kpeg"
  end
end

desc "Remove all the autogenerated RBX files"
task :clean do
  Dir["**/*.rbc"].each{|f| sh "rm -rf #{f}"}
end

Rake::TestTask.new(:test => ["lib/grammar.kpeg.rb"]) do |t|
  t.test_files = FileList['test/*_test.rb']
  # t.pattern = "test/exp_test*.rb"
  t.verbose = true
end